### ISSUE TITLE
Matrix transposition AOS -> AOSOA

### ISSUE THREAD

**Issue by roiser** [madgraph5/madgraph4gpu#215]
Here is some example code for the matrix transposition from SOA to AOSOA by using a kernel. The kernel takes several parameters which define the data structure sizes and two arrays for the input and output data. Inside the kernel one calculates the i-th page, particle, momentum, stride which is used to point to the correct element in the input array and copied over. 

```Cuda
__global__ void dev_transpose(const int* inpArr, int* outArr,
                              const int evnt_n, const int part_n,
                              const int mome_n, const int strd_n) {

  int pos = blockDim.x * blockIdx.x + threadIdx.x;
  int arrlen = evnt_n * part_n * mome_n;

  if (pos < arrlen) {

      int page_i = pos    / (strd_n * mome_n * part_n);
      int rest_1 = pos    % (strd_n * mome_n * part_n);
      int part_i = rest_1 / (strd_n * mome_n);
      int rest_2 = rest_1 % (strd_n * mome_n);
      int mome_i = rest_2 / strd_n;
      int strd_i = rest_2 % strd_n;

      int inpos = (page_i * strd_n + strd_i)   // event number
                  * (part_n * mome_n)          // event size (pos of event)
                  + part_i * mome_n            // particle inside event
                  + mome_i;                    // momentum inside particle

      printf("opos:%d, ipos:%d, page_i:%d, strd_i:%d, part_i:%i, mome_i:%d\n",
             pos, inpos, page_i, strd_i, part_i, mome_i);

      outArr[pos] = inpArr[inpos];

  }
}
```

The full code including boiler plate and Makefile is attached. 
[matrix_transposition.tar.gz](https://github.com/madgraph5/madgraph4gpu/files/6682783/matrix_transposition.tar.gz)

**Comment by valassi** [comment]
Hi @roiser, closing this - your code is included in Bridge.h and backported.

Just to confirm what we discussed in the past weeks: the "transpose" in some cases can be a memcpy. The reason is the following:

- Fortran uses this definition DOUBLE PRECISION P_MULTI(0:3, NEXTERNAL, NB_PAGE)
https://github.com/madgraph5/madgraph4gpu/blob/d0c2b02b784e3c49a9c2963e8cd112f77921002b/epoch2/fortran-cuda/pp_ttx/SubProcesses/P1_gg_ttx/auto_dsig1.f#L428

- The order of reading arrays in Fortran and C++ is indeed reversed, so the above, when read from C++, is to be interpreted as P_MULTI[NB_PAGE][NEXTERNAL][4]. At least, this is what I find 'experimentally', for instance in the tests described here https://github.com/madgraph5/madgraph4gpu/issues/329#issuecomment-1029270225. Note by the way that this is an AOS: here NB_PAGE is the "nevt" per iteration, so you have an Array of nevt Structures[NEXTERNAL][4].

- In C++ I am using an AOSOA[npagM][npar][np4][neppM] where nevt=npagM*neppM is the nevt per iterations https://github.com/madgraph5/madgraph4gpu/blob/d0c2b02b784e3c49a9c2963e8cd112f77921002b/epochX/cudacpp/ee_mumu/SubProcesses/MemoryAccessMomenta.h#L12 . This is an Array with npagM "pages" which are Structures[npar][np4] of Arrays or "pages" with neppM events per page.

- The neppM parameter can be configured. Setting it to 1 corresponds to recovering a SOA[nevt][npar][4] https://github.com/madgraph5/madgraph4gpu/blob/d0c2b02b784e3c49a9c2963e8cd112f77921002b/epochX/cudacpp/ee_mumu/SubProcesses/MemoryAccessMomenta.h#L40 . In this case this is strictly the same structure as Fortran, and (assuming both use the same fptype precision!) a memcpy is enough, https://github.com/madgraph5/madgraph4gpu/blob/5512d5ceba2f6327237e6a0d1a7c0d4914d99f50/epochX/cudacpp/ee_mumu/SubProcesses/Bridge.h#L322

I am closing this as this is all done now
