### ISSUE TITLE
Helicity initialization

### ISSUE THREAD

**Issue by jtchilders** [madgraph5/madgraph4gpu#357]
Andrea,
I ran your `madgraph4gpu/epochX/cudacpp/gg_ttgg.auto` on an NVidia A100 system we have, built with CUDA 11.4.3 & GCC 11.1.0.

I added simple print statements:
```c
printf("%s\n",__func__);
```
To `CPPProcess.cc` inside the `sigmaKin_getGoodHel()` and `sigmaKin_setGoodHel()` functions. And I noticed that these functions are executed more than I would expect. I would expect that for each execution of the binary, they should be called only once. However, I see this:
```bash
-> ./gcheck.exe -p 1 8 1
sigmaKin_getGoodHel
sigmaKin_getGoodHel
sigmaKin_getGoodHel
sigmaKin_getGoodHel
sigmaKin_getGoodHel
sigmaKin_getGoodHel
sigmaKin_getGoodHel
sigmaKin_getGoodHel
sigmaKin_setGoodHel
*******************************************************************************
Process                     = SIGMA_SM_GG_TTXGG_CUDA [nvcc 11.4.152 (gcc 11.1.0)] [inlineHel=0] [hardcodeCIPC=0]
NumBlocksPerGrid            = 1
NumThreadsPerBlock          = 8
NumIterations               = 1
<... etc....>
```

Is this expected? At first I thought I was getting the command args mixed up, but the print out seems to confirm my settings.

**Comment by valassi** [comment]
Hi Taylor, thanks. Strange, I was not expecting this.
Anyway, I wanted to look at helicities also fopr #347.
I will have a look at both...
Thanks Andrea

**Comment by valassi** [comment]
Hi @jtchilders on second thought: probably this is correct. The point is that getGoodHel is a kernel, so each execution handles only one event. (Maybe you could add to the printout also the event number, to be sure?). The algorithmic idea is the same as in the c++ or frotran verson: the way to determine the list of good helicities is by trying out a bunch of events, say 10 or so. If for one helicity an event has a 0 amplitude, most likely it is that the helicity is always bad, but a few events are tried just to exclude that you were "unlucky" in picking a particular phase space point where that helicity has a 0 ME contribution.

Note that my #347 is related, in the sense that if for the generale ME computation we use 500k events, I am now also testing 500k events to determine the good helicities. Running 10 or 1000 probably takes the same time because the GPU is idle anyway otherwise, but 500k is to omuch (and this has a cost in ggttggg). So for #347 I will reduce this to maybe even just 16 events.

But in any case fo ryour question, it s normal that you should see these 16 (or 500k!) printouts from each event that you try for helicityy filtering. Does this make sense?

Andrea

**Comment by jtchilders** [comment]
Yes, you're right, I was misinterpreting.

**Comment by valassi** [comment]
Thanks Taylor I am happy this helped, cheers Andrea
