### ISSUE TITLE
Physics results are different in fortran and cudacpp MEs at the ~permille level: different handling of top quark width

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#476]
I am stripping off as a separate issue the fine grained comparison of physics results at the E-4 to E-2 level that I am observing in ggtt* processes (in eemumu I think I get E-8 agreement if not better).

This is a followup of #417, but also #419, where the differences by factors or orders of magnitude are discussed (eg alphas, multichannel) are discussed. I will close those soon. Instead the fine grained comparison remains as a separate issue.

**Comment by valassi** [comment]
I have debugged this in PR #490.

I intially thought this was a QCD related problem, such as alphas related. Instead it is due to the handling of the top quark width:

-    fortran MEs use a top quark width hardcoded to ZERO
-    cudacpp MEs use a non-zero top-quark width

The analysis is still WIP. But we also need to understand how to handle this...

@oliviermattelaer do you have a suggestion? Is there a switch in code generation to treat the top quark as width-0? Thanks

**Comment by oliviermattelaer** [comment]
Excellent, Good catch.

Yes indeed the width has a couple of "dark magic" handling at LO which are set directly within matrix.f so far:
I do remember two of such treatment:
 - set the width of T-channel to zero (new since 2.8.x): the one problematic here
 - special handling of small width (less than 1e-6 times the mass)
and likely in the future it will be a third one 
 - remove onshell resonance within the matrix-element (but that's in the future )

The first one is related to a flag "zerowidth_tchannel" so one can turn it off/on via the command
set zerowidth_tchannel T/F
(before the generate command)

The second is related to the run_card parameter
set small_width_treatment X # where X is the threshold value


For the moment, none of them are critical in term of physics and for our target, so the best is likely to add those to the todo list of things to handle. and for the comparison, generate the code with "set zerowidth_tchannel F".

**Comment by valassi** [comment]
Thanks Olivier, I confirm that the fix works! Now I get agreement between cudacpp and fortran in the cross sections in 10+ digits also for ggtt*... a nice milestone! I will close this as it is fixed by PR #490.

I opened https://github.com/oliviermattelaer/mg5amc_test/issues/23 as a reminder that (with low priority) we should also have zero widths in cudacpp if the experiments use this...
