### ISSUE TITLE
clash between 'makefile' and 'Makefile' on case insensitive systems

### ISSUE THREAD

**Issue by oliviermattelaer** [madgraph5/madgraph4gpu#480]
Updating files: 100% (12406/12406), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:
  'epochX/cudacpp/ee_mumu.mad/SubProcesses/Makefile'
  'epochX/cudacpp/ee_mumu.mad/SubProcesses/makefile'
  'epochX/cudacpp/ee_mumu.mad/SubProcesses/P1_ll_ll/Makefile'
  'epochX/cudacpp/ee_mumu.mad/SubProcesses/P1_ll_ll/makefile'
  'epochX/cudacpp/gg_tt.mad/SubProcesses/Makefile'
  'epochX/cudacpp/gg_tt.mad/SubProcesses/makefile'
  'epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/Makefile'
  'epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/makefile'
  'epochX/cudacpp/gg_ttg.mad/SubProcesses/Makefile'
  'epochX/cudacpp/gg_ttg.mad/SubProcesses/makefile'
  'epochX/cudacpp/gg_ttg.mad/SubProcesses/P1_gg_ttxg/Makefile'
  'epochX/cudacpp/gg_ttg.mad/SubProcesses/P1_gg_ttxg/makefile'
  'epochX/cudacpp/gg_ttgg.mad/SubProcesses/Makefile'
  'epochX/cudacpp/gg_ttgg.mad/SubProcesses/makefile'
  'epochX/cudacpp/gg_ttgg.mad/SubProcesses/P1_gg_ttxgg/Makefile'
  'epochX/cudacpp/gg_ttgg.mad/SubProcesses/P1_gg_ttxgg/makefile'
  'epochX/cudacpp/gg_ttggg.mad/SubProcesses/Makefile'
  'epochX/cudacpp/gg_ttggg.mad/SubProcesses/makefile'
  'epochX/cudacpp/gg_ttggg.mad/SubProcesses/P1_gg_ttxggg/Makefile'
  'epochX/cudacpp/gg_ttggg.mad/SubProcesses/P1_gg_ttxggg/makefile'

I guess we have to change those name to _fortran _cuda instead

**Comment by valassi** [comment]
Hi Olivier, thanks. For curiosity is this Windows or Mac?

Good point anyway, having 'makefile' and 'Makefile' was very ugly to start with. 

This is related to issue #413. There I was suggesting
- keep the madevent "makefile" as main
 - rename the cudacpp as "plugin.mk" (to also foresee alpaka etc), and call it from the madevent makefile
 - for standalone cudacpp, add a symlink of plugin.mk to Makefile (or makefile) so that one can simply type "make" without "-f", as presently done

This is also related to #400 (of which #413 is a spinoff). I guess both of those can be closed when this issue is fixed.

**Comment by valassi** [comment]
This will be fixed by PR #484 that I am about to merge. 

I renamed the cudacpp Makefile as cudacpp.mk.
I then add a symlink of that as makefile (lowercase) so that in standalone mode a 'make' works without the need for '-f'.
In madevent+cudacpp mode, the madeven code generation overwrites that makefile symlink (the cudacpp makefile) with its own makefile file (the madevent makefile, which includes also a call to cudacpp.mk, #400).

Closing.
