### ISSUE TITLE
src/makefile is not installation independent

### ISSUE THREAD

**Issue by oliviermattelaer** [madgraph5/madgraph4gpu#55]
we have issue with various variable
  * CUINC=/usr/local/cuda/targets/x86_64-linux/include
  * CXX=g++

**Comment by valassi** [comment]
Hi @oliviermattelaer thanks.

I guess both things can be fixed with cmake, but I am not sure you want to use cmake for the upstream madgraph (do you?).

How do you typically write Makefiles now, and what could be acceptable, eg also for cuda? Should the maefile assume CUINC has been set in advance before calling make for instance?

Andrea

**Comment by hageboeck** [comment]
Since `CXX` is actually an implicit variable, we need not even set it from within the makefile. I propose to
- [ ] remove it
- [ ] make it optional via
```
CXX ?= g++
```
This way, you can set it from the outside using the environment if necessary.

I have a PR up that's making cuda optional. I could have a look at how to make cuda more system independent. 

@oliviermattelaer where/how would we find cuda on your machine?

And yes, cmake could do that for us.

**Comment by oliviermattelaer** [comment]
I like the second option I have implemented 
for the question "where/how would we find cuda on your machine?" 
I'm not yet at compiling the new code on my machine, but since this line is nothing new I guess the path is also valid on my cluster.

**Comment by hageboeck** [comment]
One more thing:
I just talked with Stefan, and we think that setting CUDA_HOME as an environment variable would make sense. From there, the Makefile will itself find
```
NVCC ?= ${CUDA_HOME}/bin/NVCC
CUINC ?= -I${CUDA_HOME}/include
CULINK ?= -L${CUDA_HOME}/lib64/ ...
```
This way, it *should* work, but you can override it if your cuda installation is a little different.

I will implement it like this in my work for the tests. Let me know if you want it renamed.

**Comment by oliviermattelaer** [comment]
I like it, will include it in my MG5 port

**Comment by valassi** [comment]
Hi @hageboeck thanks I also like the optional definition with "?" 👍 and the top-level CUDA_HOME 👍
