### ISSUE TITLE
Problem for CKKW merging algorithm

### ISSUE THREAD

**Issue by oliviermattelaer** [madgraph5/madgraph4gpu#645]
crash in the pure fortran vectorised code

```
generate p p > ta+ ta-
add process p p > ta+ ta- j
#add process p p > ta+ ta- j j
output PROC_sm_2 --vector_size=2
launch
set ickkw 1
set mc_grouped_subproc F
```

Findings so far:
 - issue is the behaviour of the findmt function
 - difference with vector_size is the value of iconfig when reaching that routine.
    - When running G2 the vectorised code hase iconfig set to 1 and not to 2

**Comment by oliviermattelaer** [comment]
Fixed issue: https://github.com/mg5amcnlo/mg5amcnlo/commit/ef334c58232d83d939c8a8d89b59b833cc237469
@roiser @valassi

**Comment by valassi** [comment]
Thanks Olivier! For reference, this is relevant to the CMS process suggested by Sapta

They use these cards
https://github.com/cms-sw/genproductions/tree/mg29x/bin/GenValidation/updated_validation_cards/dy_mlm_mll50

And they generate the gridpack with this code: 
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/gridpack_generation.sh

**Comment by roiser** [comment]
Hi Olivier, thanks, was this the issue in "cluster.f" we discussed earlier? cheers

**Comment by valassi** [comment]
For the record, I confirm that this is fixed in commit https://github.com/mg5amcnlo/mg5amcnlo/commit/6d2182cc197e9383a2aa4fb834e51d72faa4e6c2 which I am now using in madgraph4gpu (see MR #654, in https://github.com/madgraph5/madgraph4gpu/pull/654/commits/57d8ec3eb1d342c8bbd31abef6f9a58960012978), while I can reproduce an error after launch in https://github.com/mg5amcnlo/mg5amcnlo/commit/c1d10f42631378d4c5ea6f594c9318cedff72953

So this is definitely fixed
