### ISSUE TITLE
[Errno 2] No such file or directory: '...SubProcesses/P1_gg_ttx/Hel/selection'

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#789]
Hi @oliviermattelaer minor issue but I do not like errors ;-) I assign this to you.

This is gpucpp

```
set stdout_level DEBUG
set zerowidth_tchannel F
generate g g > t t~
output madevent ../TMPOUT/CODEGEN_mad_gg_tt --hel_recycling=False --vector_size=16384 --me_exporter=standalone_cudacpp
launch
```

This eventually prints
```
...
Compiling the bias module 'dummy'
Using random number seed offset = 21
INFO: Running Survey 
Creating Jobs
Working on SubProcesses
[Errno 2] No such file or directory: '/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/TMPOUT/CODEGEN_mad_gg_tt/SubProcesses/P1_gg_ttx/Hel/selection'
INFO:     P1_gg_ttx  
Building madevent in madevent_interface.py with 'CPP' matrix elements
INFO:  Idle: 1,  Running: 0,  Completed: 0 [ current time: 09h19 ] 
INFO:  Idle: 0,  Running: 0,  Completed: 1 [  4.1s  ] 
INFO:  Idle: 0,  Running: 0,  Completed: 1 [  4.1s  ] 
INFO: End survey 
...
```

Thanks Andrea

**Comment by oliviermattelaer** [comment]
Hi,

This "error" is only printed when you are in debugging mode. This is already completely normal/something that I want to see since this is related to helicity recycling not setup.

So if ones want to fix this, this needs to be fixed outside of the madgraph4gpu project (since this is not related at all).
One thing that could be cool is to use that setup to compute the (non)zero helicity and in that case as a side effect we will also not have that information line.
