### ISSUE TITLE
generate_events tries to remove GpuAbstraction.h

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#947]
Trying to create a gridpack and use generate_events I get
```
INFO: Creating gridpack 
Command "generate_events -f" interrupted with error:
OSError : Cannot call rmtree on a symbolic link
Please report this bug on https://bugs.launchpad.net/mg5amcnlo
More information is found in '/data/avalassi/GPU2023/madgraph4gpuX/epochX/cudacpp/gg_tt.mad/run_01_tag_1_debug.log'.
Please attach this file to your report.
removing %s /data/avalassi/GPU2023/madgraph4gpuX/epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/GpuAbstraction.h
```

(I had to add a manual print to show the path, because of https://github.com/mg5amcnlo/mg5amcnlo/issues/123)

I guess it just tries to delete G* and it does not expect GpuAbstraction.h, which it should not remove...

**Comment by valassi** [comment]
This is a possible fix https://github.com/madgraph5/madgraph4gpu/pull/948/commits/8e290296a0eca4d42ea90aaefb18197a9f95696c

@oliviermattelaer I guess this is best only in cudacpp, but maybe you have better ideas

(Yes I know this is using patches, but this is what we have now, and this file is already included there)

**Comment by oliviermattelaer** [comment]
Hi Andrea,

Sorry but not, python file CAN NOT be modified via patch.
For python file, this is not a question of style of coding/support/...

It is just WRONG to do that, the reason is that the code has priority to use MG5DIR/madgraph/interface/madevent_interface.py (same for other file) over bin/internal/madevent_interface.py
But since you do not patch (and you should not) MG5DIR/madgraph/interface/madevent_interface.py 
the effect of the patch will be applied for some user and not for others.

I did implement the full framework needed to avoid any patch to any python file, so for sure we do not need any patch for any python file. We can do a peer programing together if you want to see how such change need to be properly handle if you want (or I can do it and you take a look, as you want)

**Comment by valassi** [comment]
> (Yes I know this is using patches, but this is what we have now, and this file is already included there)

Specifically, my mistake: "this file is already included there" was wrong, you had already removed it

**Comment by valassi** [comment]
> I did implement the full framework needed to avoid any patch to any python file, so for sure we do not need any patch for any python file

Thanks again. I confirm that now my patches are created without any check on .py files. (I added a comment in #948 using https://github.com/mg5amcnlo/mg5amcnlo/pull/125)

**Comment by valassi** [comment]
This is fixed in https://github.com/mg5amcnlo/mg5amcnlo/pull/125

Submodule being updated in PR #949

Closing
